services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*" # required, may need port.
      PUID: 1000 # optional, your user id
      PGID: 999 # optional, your group id
    ports:
      - 3333:3000
    volumes:
      - /docker/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
    networks:
      - npm_net
    
networks:
  npm_net:
    external: true
    name: npm_net
